### ISSUE TITLE
有sf的影子

### ISSUE THREAD

**Issue by fucongcong** [JanHuang/fastD#1]
嗯嗯，确实还是有那么一点，只是有那么一点点啦，没有sf那么神，因为有参照过symfony和laravel来做。当然会慢慢发展自己的风格。

**Comment by JanHuang** [comment]
嗯嗯，确实还是有那么一点，只是有那么一点点啦，没有sf那么神，因为有参照过symfony和laravel来做。当然会慢慢发展自己的风格。
