### ISSUE TITLE
DatabasePool缺少reconnect机制

### ISSUE THREAD

**Issue by yyz26371945** [JanHuang/fastD#13]
目前发现一个bug，连接mysql，当框架的db连接的wait时间超过mysql的wait_timeout配置后，框架所有的db连接会不可用。这时通过getConnection($key)其实获取的是一个无效连接，造成数据库操作失败。

**Comment by JanHuang** [comment]
可以提供代码不，我好跟踪调试，感谢。如果数据库存在这个问题，我相信其他也会有这个隐患。

**Comment by yyz26371945** [comment]
复现其实很简单，只要在mysql配置里面把wait_timeout调小，比如设置100，然后启动框架，这时候通过mysql命令show processlist可以看到当前mysql的所有连接，里面包含框架的，状态应该是Sleep。
然后100s之后，再次查看，会发现连接已经没了，这会在框架里获取到的连接就是不可用的了。

**Comment by JanHuang** [comment]
好的，我稍后验证一下，感谢🙏

**Comment by JanHuang** [comment]
@yyz26371945 已添加连接存活检测，基础测试可用，不过我还需要深入测试和其他因素测试。可以先尝尝鲜。感谢反馈

**Comment by yyz26371945** [comment]
好的，我测试一下，多谢多谢

**Comment by yyz26371945** [comment]
![image](https://cloud.githubusercontent.com/assets/20291334/24905795/c090d94a-1ee7-11e7-8c31-3ad213175f44.png)
试了下，这块实现有点问题：
1.这样会造成2次查询，如果用户的查询数据多或者比较耗时，这块成本是比较大的；
2.建议这块改成ping的方式，探活，但是我刚刚查了下pdo的实现里面没ping相关的函数。。。

**Comment by JanHuang** [comment]
恩，是的。ping的方式天峰已经给出了不使用的原因，详细请看: https://wiki.swoole.com/wiki/page/350.html 其实这里不会产生两次查询，如果连接断开了，顶多就到了构建语句的环节，因为断开了，所以不会产生查询，损耗在代码组装上，可忽略。

**Comment by yyz26371945** [comment]
不是，我是刚刚看mysql log发现的，正常情况下是会产生两次查询的，因为第一次查询后，是有结果的，if分支失效，然后就到了parent::query($query)这句了，就产生了第二次查询

**Comment by yyz26371945** [comment]
不是，我是刚刚看mysql log发现的，正常情况下是会产生两次查询的，因为第一次查询后，是有结果的，if分支失效，然后就到了parent::query($query)这句了，就产生了第二次查询

**Comment by JanHuang** [comment]
哈哈，还真是，看来写懵了，我回头改一下
