### ISSUE TITLE
路由RESTful 设置问题

### ISSUE THREAD

**Issue by loyating** [JanHuang/fastD#31]
Server: fast-d(3.1)
App version 2.0.0 (dev)
Swoole version 1.9.10

Fatal error: Uncaught Error: Class 'UserController' not found
$vendor/fastd/routing/src/RouteMiddleware.php:48

```php
$route = route();

$route->get('/', 'IndexController@index');

$route->group('/user', function ($route) {
    $route->get('/', 'UserController@get');
    $route->post('/', 'UserController@post');
    $route->put('/', 'UserController@put');
    $route->delete('/', 'UserController@delete');
});
```

get、post没问题，put、delete就报错

**Comment by JanHuang** [comment]
@loyating 收到反馈，我去检查一下。

**Comment by loyating** [comment]
话说能否建个QQ群？

**Comment by loyating** [comment]
文档：
route()->group('/v1', function () {
    route()->get('/', 'IndexController@sayHello');
});

测试：
访问 /v1/    ok
访问 /v1     404

**Comment by JanHuang** [comment]
@loyating QQ群: eashPHP-Swoole 633921431 里面可以找到我

**Comment by JanHuang** [comment]
@loyating 已修复
