### ISSUE TITLE
DatabasePool在实例database时存在不足

### ISSUE THREAD

**Issue by fengzhi** [JanHuang/fastD#32]
database继承Medoo，Medoo在实例PDO时有option、cammand等参数，比如option用于PDO::setAttribute()来设定PDO的一些预常量，常见的如$this->pdo->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION)，在$db->exec($query)时如果$query错误才会抛出异常。建议在pool实例database时加入
'option' => isset($config['option']) ? $config['option'] : ''等Medoo配置

**Comment by JanHuang** [comment]
感谢反馈，会尽快实现🙏

**Comment by JanHuang** [comment]
@fengzhi 您好，已支持。

**Comment by fengzhi** [comment]
👍效率
