### ISSUE TITLE
框架不支持用Nginx的反向代理接收请求

### ISSUE THREAD

**Issue by yyz26371945** [JanHuang/fastD#34]
我将框架升级到最新之后，发现一直报错
PHP Fatal error:  Uncaught InvalidArgumentException: The source URI string appears to be malformed in /home/www/log-api/vendor/fastd/http/src/Uri.php:400
然后追查后发现，是因为调用ServerRequest::createUriFromGlobal函数时，生成的uri错误，缺失了host信息
进一步追查发现，这个问题只有在启用nginx反向代理转发请求才会发生，而直接请求发送到框架是没问题的
最后，发现swoole_http_request对象，如果启用了nginx反向代理
那么header里的host值即为ip
![image](https://cloud.githubusercontent.com/assets/20291334/26245078/168c19d6-3cc5-11e7-8381-cd221ff89db5.png)

如果直接发送，则是ip:port的形式
![image](https://cloud.githubusercontent.com/assets/20291334/26245035/ddb8a9d0-3cc4-11e7-9588-b2dbbd8e197e.png)

以下代码获取host变量的时候就会存在问题，反向代理直接为null
![image](https://cloud.githubusercontent.com/assets/20291334/26244998/b41efb9c-3cc4-11e7-9c06-ffe24fbe6417.png)
所以就会引发bug

**Comment by JanHuang** [comment]
@yyz26371945 感恩反馈

**Comment by JanHuang** [comment]
应该可以从 SwooleRequestServer 中修改那个判断
```php
$host = isset($request->header['host']) ? $request->header['host'] : $request->header['server_addr'];
        $info = parse_url($host);
        if (isset($info['host'])) {
            $host = $info['host'];
        }
```
@yyz26371945

**Comment by yyz26371945** [comment]
嗯，目前我这边就是改了下判断逻辑，现在测试是没问题了，其它的我再回归一下看看

**Comment by JanHuang** [comment]
@yyz26371945 恩，可以的话，根据您那边的修改给我发个PR。https://github.com/JanHuang/http

**Comment by yyz26371945** [comment]
好的

**Comment by JanHuang** [comment]
@yyz26371945 感谢。3.1分支
