### ISSUE TITLE
当MySQL的连接超过wait_timeout的时候，第一次会抛出ErrorException，而不是PDOException

### ISSUE THREAD

**Issue by yyz26371945** [JanHuang/fastD#42]
如题，我用的是最新版本的框架，今天发现好多的异常，追查后发现是因为第一次连接失效的时候，抛出的异常是ErrorException，异常码是0，异常信息是PDO::query(): MySQL server has gone away，查询失败。但是第二次再query的时候，抛出的异常就变为了PDOException，就可以触发reconnect机制

**Comment by JanHuang** [comment]
@yyz26371945 恩恩。这个问题我们内部已经发现了，并且已经解决了，不过暂时还没合并更新，需要观察一下，确定后会及时更新。感谢反馈

**Comment by yyz26371945** [comment]
恩，好的，每次都回复好快:)

**Comment by JanHuang** [comment]
@yyz26371945 算是咱们的产品吧。会不断完善，当然会重视一些，欢迎建议。😆

**Comment by RunnerLee** [comment]
@yyz26371945 已修复
