### ISSUE TITLE
Application . 加载问题

### ISSUE THREAD

**Issue by loyating** [JanHuang/fastD#46]
bootstrap初始化，在注册异常回调和增加logger服务中间发生异常，会获取不到logger服务

**Comment by JanHuang** [comment]
@loyating 有具体代码吗?

**Comment by loyating** [comment]
![image](https://user-images.githubusercontent.com/5088390/28904105-4935f904-783b-11e7-8cd7-adecadcc6c28.png)
红框中加载配置文件时候发生了异常，然后直接走异常回调：
![image](https://user-images.githubusercontent.com/5088390/28904142-710ea2be-783b-11e7-93c2-f52c655a01c8.png)
Fatal error: Uncaught FastD\Container\Exceptions\ServiceNotFoundException: Service "logger" not found in $/vendor/fastd/container/src/Container.php:73

**Comment by JanHuang** [comment]
@loyating 因为逻辑上app.php配置文件是需要先行确定是否存在的，这个是必须满足的条件。如果因为配置文件不存在发生的错误，我们会继续想办法提高提示的体验。感谢反馈

**Comment by loyating** [comment]
恩恩
