### ISSUE TITLE
ORM支持有计划吗？

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#47]
ORM支持有计划吗？或者有没有快速继承ORM的方法

**Comment by JanHuang** [comment]
@hadilee 你好，已经有小伙伴集成了。可以前往: https://github.com/zqhong/fastd-eloquent

**Comment by hadilee** [comment]
谢谢，棒棒的

**Comment by JanHuang** [comment]
@hadilee 不客气，如果在使用过程中有遇到问题或者其他想法，可以及时跟咱们联系，感谢您的支持。😁
