### ISSUE TITLE
消息队列如何使用

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#48]
你好，有这样一个需求，批量给APP推送消息，因为量比较大想用消息队列做，该如何实现，谢谢

**Comment by JanHuang** [comment]
@hadilee 你是想通过框架去实现吗?

**Comment by hadilee** [comment]
是的，可以实现吗？

**Comment by JanHuang** [comment]
@hadilee 理论上可以实现，但是需要改动的东西可能会比较多。并且你需要知道你想达到什么效果，这样才好去调整。

**Comment by hadilee** [comment]
后台定期给所有的用户（app）推送系统消息，用户量比较大，如果直接用php代码循环肯定会卡死，想法是把需要发送的消息放在队列里。如果不用FD框架，其他方式实现有没有好的建议，谢谢

**Comment by JanHuang** [comment]
kafka 应该可以助你一臂之力。php 扩展可以看看这个: [kafka-php](https://github.com/weiboad/kafka-php)
又或者可以参考现成一些方案。应用消息推送。

**Comment by hadilee** [comment]
Swoole的消息队列，我以为可以运用到我的这个场景中

**Comment by JanHuang** [comment]
@hadilee 你也可以尝试，毕竟机制是一样的。
