### ISSUE TITLE
你好，swoole模式下运行，怎样做可以代码热部署

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#53]
你好，
1、swoole模式下运行，怎样做可以代码热部署？
2、用php内置代理服务器和swoole模式运行，功能效果是一样的吗？不考虑性能

**Comment by JanHuang** [comment]
1. swoole 模式下运行热部署是有一定的问题，所以在3.2版本中会优化这个问题。
2. 如果不考虑性能问题，php内置服务器和swoole运行效果是一样的，要注意的是，如果部分功能是依赖swoole的话，推荐使用swoole。但是推荐php内置服务器作为开发，生产情况下可以通过swoole加速应用。
