### ISSUE TITLE
你好，如何在所有接口加密钥验证

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#54]
你好,

1、如何做到在所有接口增加密钥（自定义密钥）验证？
2、App如何保持登录状态，之前用cookie/session方式?

**Comment by JanHuang** [comment]
1. 可以尝试使用中间间的方式.
```php
route()->group(["/", 'middleware' => '你的校验规则'], function () {
    // 你的路由
});
```

2. 可以沿用cookie的形式，Response中有提供cookie处理的。

**Comment by hadilee** [comment]
谢谢，但是在swoole模式下，cookie,session还能生效吗？是不是需要用redis共享登陆用户信息

**Comment by JanHuang** [comment]
@hadilee session 其实也是基于cookie进行存储的，可以利用这个原理，cookie还是可以用的，至于Session的话需要有一些微调

**Comment by hadilee** [comment]
你好，看到Response中有关cookie的处理withCookie()函数，但没调试成功，设置后在浏览器中没有看到cookie值，cookie中也没有看到session_id

**Comment by hadilee** [comment]
或者还有没有不用cookie实现登陆用户信息管理的方法

**Comment by JanHuang** [comment]
@hadilee 可以提供代码吗?

**Comment by hadilee** [comment]
use FastD\Http\ServerRequest;
use FastD\Http\Response;
class WelcomeController
{
    protected $response;
    public function __construct(){
        $this->response = new Response();
    }

    public function welcome(ServerRequest $request)
    {

        $this->response->withCookie('uid',100,900);


        return json([
            'msg' => array('name'=>'hello','data'=>1),
        ],200);

    }
}

**Comment by JanHuang** [comment]
@hadilee 您好，原因是这样子的。您此处的 `$this->response` 并没有返回给调度器，因此您返回的 `json` 函数中的 `Response` 是并没有设置 cookie 的，您可以试试

```php
public function welcome(ServerRequest $request)
{
        $this->response->withCookie('uid',100,900);
        $this->response->withContent(json_encode([
            'msg' => array('name'=>'hello','data'=>1),
        ]));
        return $this->response;
}
```

或者

```php
public function welcome(ServerRequest $request)
    {
        return json([
            'foo' => $request->getParam('foo', 'bar'),
        ])->withCookie('uid',100,900);
    }
```

`json` 函数本身会新建一个全新的响应对象，因此您此处的 $this->response 其实是并没有对response进行操作的，两个独立的对象。

源代码:
```php
function json(array $content = [], $statusCode = Response::HTTP_OK)
{
    return new JsonResponse($content, $statusCode);
}
```

**Comment by hadilee** [comment]
响应头有了，但在浏览器中的cookie中还是查不到

Set-Cookie | uid=100; expires=Thu, 01-Jan-1970 00:15:00 GMT

**Comment by JanHuang** [comment]
@hadilee 确实，估计是有bug，请稍等

**Comment by JanHuang** [comment]
@hadilee 已修复

**Comment by hadilee** [comment]
如何升级我的代码，composer update吗？

**Comment by JanHuang** [comment]
是的。composer update fastd/http 单独更新也可
