### ISSUE TITLE
如何在 Controller 以正确的姿势 header 信息?

### ISSUE THREAD

**Issue by xsharp** [JanHuang/fastD#55]
hi，好，这不是一个 issue。
如题。
----------
目前的做法是新建一个 Class 继承 \FastD\Application，然后覆写 run() 方法，比如：
```
	$request = ServerRequest::createServerRequestFromGlobals(); // 原有代码
	$response = $this->handleRequest($request); // 原有代码

	// 在这里增加 header 动作，具体 header 信息在 Controller 中设置，通过一个 Container 暂存 header 信息
	$response = $response->withHeaders(...);

	$this->handleResponse($response); // 原有代码
	return $this->shutdown($request, $response); // 原有代码
```
还有一种方法，就是通过 middleware 实现，在 Dispatcher::before() 中执行，但感觉对使用者也不友好。

不知道是否有更好的方式？

**Comment by JanHuang** [comment]
@xsharp 您是想获取Request 的 header信息还是在Response上自定义header信息呢?

**Comment by xsharp** [comment]
是想在 Response 中输出新的 header 信息，不好意思，没有描述清楚。

**Comment by JanHuang** [comment]
@xsharp 是可以的，只要你在控制器的Response对象中设置即可。

```php
return json([
            'msg' => 'hello dobee',
        ])->withHeader('key', 'value');
```

这样能否满足您的需求?

**Comment by JanHuang** [comment]
只要是一个 Response 对象，就可以随意对其进行设置，然后最终返回给 `Application` 处理。这样就可以按照设置的进行数据输出

**Comment by xsharp** [comment]
感谢。
关了，n 种方法了，舍近求远了，之前想当然了，没注意到 Controller 是可以直接返回一个 Response 对象。`return json([])->withHeader(...)` 这种方式最优雅。

**Comment by JanHuang** [comment]
@xsharp 哈哈，欢迎提供更多的建议。
