### ISSUE TITLE
你好，中间件对post无效？

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#60]
你好，中间件对post无效？
route()->**post**('/abc', 'WelcomeController@welcome')->withMiddleware('validator');

$_GET就就可以
route()->get('/abc', 'WelcomeController@welcome')->withMiddleware('validator');

**Comment by JanHuang** [comment]
可以的。请问你是怎么操作的呢?

**Comment by hadilee** [comment]
必须在handle中调用abort()才可以吗？我设计的这个中间件的出发点是，验证API接口必传的几个参数如_Sign

**Comment by JanHuang** [comment]
不一定，但是得在生命周期内执行即可。具体post的话也是可以的。可以参考: [cache middleware](https://github.com/JanHuang/fastD/blob/master/src/Middleware/CacheMiddleware.php)

**Comment by hadilee** [comment]
增加了一个中间件，但没生效
1、已在配置文件中配置
'validator' => [\Middleware\LoginSucessValidator::class]
2、路由配置
route()->post('/abc', 'WelcomeController@welcome')->withMiddleware('validator');

3、中间件代码
use FastD\Http\Response;
use FastD\Middleware\DelegateInterface;
use FastD\Middleware\Middleware;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class LoginSucessValidator extends Middleware
{
    /**
     * @param ServerRequestInterface $request
     * @param DelegateInterface $next
     * @return ResponseInterface
     */
    public function handle(ServerRequestInterface $request, DelegateInterface $next)
    {
        $_SessionKey = $request->getParam('_SessionKey');
        if(empty($_SessionKey)){
            $_data = array(
                'status' => 0,
                'msg' => '参数错误',
            );
            return json($_data);
            //return new Response($_data, Response::HTTP_OK, array());
            //return new JsonResponse($_data, 200);

        }
        return $next->process($request);
    }
}

**Comment by hadilee** [comment]
服务器报错
Middleware\\LoginSucessValidator，多了一个斜杠

PHP Fatal error:  Class 'Middleware\\LoginSucessValidator' not found in /var/www/html/zrt/vendor/fastd/routing/src/RouteDispatcher.php on line 83

**Comment by JanHuang** [comment]
您稍等等一下，我尝试复现你的问题

**Comment by JanHuang** [comment]
@hadilee 您好，按照你的步骤和操作，是证实不会出现问题的。对比一下是否那个位置出现缺漏了?
app.php
```php
<?php
/**
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2016
 *
 * @see      https://www.github.com/janhuang
 * @see      http://www.fast-d.cn/
 */

return [
   // code
    'middleware' => [
        'validator' => [\Middleware\LoginSucessValidator::class]
    ],
];
```

routes.php
```php
route()->post('/abc', 'WelcomeController@welcome')->withMiddleware('validator');
```

Middleware\LoginSucessValidator

```php
<?php
/**
 * @author    jan huang <bboyjanhuang@gmail.com>
 * @copyright 2017
 *
 * @see      https://www.github.com/janhuang
 * @see      http://www.fast-d.cn/
 */

namespace Middleware;


use FastD\Middleware\DelegateInterface;
use FastD\Middleware\Middleware;
use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;

class LoginSucessValidator extends Middleware
{
    /**
     * @param ServerRequestInterface $request
     * @param DelegateInterface $next
     * @return ResponseInterface
     */
    public function handle(ServerRequestInterface $request, DelegateInterface $next)
    {
        $_SessionKey = $request->getParam('_SessionKey');
        if(empty($_SessionKey)){
            $_data = array(
                'status' => 0,
                'msg' => '参数错误',
            );
            return json($_data);
        }
        return $next->process($request);
    }
}
```

**Comment by hadilee** [comment]
不好意思，耽误您这么长时间，是我拼写错误，类文件名和类名不一直，应该是LoginSuccessValidator，写成了LoginSucessValidator，少了一个字母c

**Comment by JanHuang** [comment]
@hadilee 好的，没关系。帮助大家解决问题也是咱们乐意做的事情
