### ISSUE TITLE
你好，公共函数如何规划？

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#61]
一些公共函数，如随机字符串、加密有函数，计划放src\Server中，在控制器中如何引用

namespace Services;
class UserServer
{
	public function random_str(){}
}

**Comment by JanHuang** [comment]
这个是非常简单的。
首先框架是使用composer进行管理的。那么你可以随意的创建辅助函数的文件，如: helpers.php
在composer.json 中的 autoload中加入:

```json
"autoload": {
        "files": [
            "helpers.php"
        ]
    },
```
即可完成你的辅助函数。
在控制其中使用跟使用普通函数一样: `array_map` 或者 `json` 一样。
