### ISSUE TITLE
你好，如何设置错误等级？

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#64]
现在notice都会中断程序，如何设置只有在错误时中断程序
{
    "msg": "Undefined index: view_info",
    "code": 0
}

**Comment by RunnerLee** [comment]
你好, 其实并不建议调整错误等级. 
借用 [php.net](http://php.net/manual/zh/errorfunc.configuration.php#ini.error-reporting) 的一句话
```
严格的信息将帮助你使用最新和最好的建议的方法来编写代码
```

**Comment by hadilee** [comment]
@RunnerLee 谢谢
你好，还有个问题请教
如何在model层获取表前缀，我要在model层直接$this-db->query($sql)，所以要用到表前缀
