### ISSUE TITLE
你好，路由找不到，已经配置了

### ISSUE THREAD

**Issue by hadilee** [JanHuang/fastD#69]
路由配置
route()->post('/myschedule', 'ScheduleController@schedule_running');//计划任务

报错信息
```
{
    "msg": "Route \"/%08myschedule\" is not found.,File=endor/fastd/routing/src/RouteCollection.php,Line=276",
    "code": 404
}
```

**Comment by loyating** [comment]
/%08myschedule
你这请求地址写错了吧，%08 空格？

**Comment by hadilee** [comment]
@loyating 确定没有空格，有些奇怪
`route()->post('/myschedule', 'ScheduleController@schedule_running');//计划任务`

**Comment by loyating** [comment]
不是说你配置文件中写了空格，发起请求时候的地址
