### ISSUE TITLE
关于API版本问题

### ISSUE THREAD

**Issue by CaoDongDong1991** [JanHuang/fastD#7]
请教一个问题，有时候我们给出去的API接口可能会存在 1.0 版本、2.0版本等不同版本，这种情况下您建议怎么做呢？是新开一个接口或者其他什么呢？

**Comment by JanHuang** [comment]
首先我们要对版本这个概念有一个统一的理解，我们对于大版本的升级，是不会向下兼容的，就比如你说的1.0，2.0这样的版本，也就是说，2.0 的功能不一定在1.0 上完全兼容，而1.0 的不一定能在2.0上直接使用，所以如你所说，我个人建议是分开不同的的 API，直到旧版的被淘汰。

**Comment by CaoDongDong1991** [comment]
谢谢

**Comment by JanHuang** [comment]
不客气
