### ISSUE TITLE
是否支持热加载

### ISSUE THREAD

**Issue by hooklife** [JanHuang/fastD#70]
是否支持热加载

**Comment by JanHuang** [comment]
@hooklife 你好，暂时还不支持热加载。而且线上环境并不建议使用热加载。如果是开发环境需要，可以是用php内置web服务器进行开发。
```php
php -S localhost:9876 -t web
```
到了线上的话切换到swoole运行即可。

**Comment by hooklife** [comment]
好的，十分感谢
